### ISSUE TITLE
failed load banks (a table) in select url option

### ISSUE THREAD

**Issue by VahidMolaeiRad** [owlpro/jelly#1]
# my code
```
import React, { Component } from 'react'
import DTK from '../../datatable_keys'
import {SmartCrud} from 'jelly-smart-crud'

const access = JSON.parse(localStorage.getItem('access'))

class Terminals extends Component {
    state = {
        editModal: {
            show: false,
            data: null,
        },
    }
    columns = [
        {
            name: 'نام',
            selector: 'title',
            sortable: false,
            grow: 2,
        },
        {
            name: 'بانک',
            selector: 'bank.name',
            sortable: false,
            grow: 1,
            
        },
        {
            name: 'سریال',
            selector: 'serial',
            sortable: false,
            grow: 2,
        },
        {
            name: 'ترمینال',
            selector: 'terminal_id',
            sortable: false,
            grow: 2,
        },
        {
            name: 'IMEI',
            selector: 'imei',
            sortable: false,
            grow: 3,
        },
    ]
    filter = []
    inputs = [
        {
            selector: 'title',
            type: 'text',
            label: 'نام',
            col: 4,
            isRequired: true,
            editable: true,
        },
        {
            selector: 'bank.name',
            type: 'select',
            label: 'بانک متصل کننده',
            col: 4,
            options: `/api/v4/banks`,
            isRequired: true,
            editable: true,
        },
        {
            selector: 'brand',
            type: 'text',
            label: 'برند',
            col: 4,
            isRequired: true,
            editable: true,
        },
        {
            selector: 'model',
            type: 'text',
            label: 'مدل',
            col: 4,
            isRequired: true,
            editable: true,
        },
        {
            selector: 'serial',
            type: 'text',
            label: 'سریال',
            col: 4,
            isRequired: true,
            editable: true,
        },
        {
            selector: 'terminal_id',
            type: 'text',
            label: 'ترمینال',
            col: 4,
            isRequired: true,
            editable: true,
        },
        {
            selector: 'imei',
            type: 'text',
            label: 'IME',
            col: 4,
            isRequired: true,
            editable: true,
        },
    ]
    render() {
        return (
            <React.Fragment>
                <SmartCrud
                    title="لیست دستگاه ها  "
                    inputs={this.inputs}
                    editable
                    deletable
                    //debug
                    mutators={{
                        onEdit: (data) => {
                            console.log(data)
                            return data
                        },
                        onSubmit: (data) => {
                            console.log(data)
                            return data
                        },
                        onSubmitEdit: (data) => {
                            console.log(data)
                            return data
                        },
                    }}
                    route={DTK.TERMINALS}
                    columns={this.columns}
                    filters={this.filter}
                    relations={['bank']}
                    //appendFilter={[['application.clubs.id', '=', access.club.id]]}
                />
            </React.Fragment>
        )
    }
}
export default Terminals

```

**Comment by owlpro** [comment]
> # my code
> ```
> import React, { Component } from 'react'
> import DTK from '../../datatable_keys'
> import {SmartCrud} from 'jelly-smart-crud'
> 
> const access = JSON.parse(localStorage.getItem('access'))
> 
> class Terminals extends Component {
>     state = {
>         editModal: {
>             show: false,
>             data: null,
>         },
>     }
>     columns = [
>         {
>             name: 'نام',
>             selector: 'title',
>             sortable: false,
>             grow: 2,
>         },
>         {
>             name: 'بانک',
>             selector: 'bank.name',
>             sortable: false,
>             grow: 1,
>             
>         },
>         {
>             name: 'سریال',
>             selector: 'serial',
>             sortable: false,
>             grow: 2,
>         },
>         {
>             name: 'ترمینال',
>             selector: 'terminal_id',
>             sortable: false,
>             grow: 2,
>         },
>         {
>             name: 'IMEI',
>             selector: 'imei',
>             sortable: false,
>             grow: 3,
>         },
>     ]
>     filter = []
>     inputs = [
>         {
>             selector: 'title',
>             type: 'text',
>             label: 'نام',
>             col: 4,
>             isRequired: true,
>             editable: true,
>         },
>         {
>             selector: 'bank.name',
>             type: 'select',
>             label: 'بانک متصل کننده',
>             col: 4,
>             options: `/api/v4/banks`,
>             isRequired: true,
>             editable: true,
>         },
>         {
>             selector: 'brand',
>             type: 'text',
>             label: 'برند',
>             col: 4,
>             isRequired: true,
>             editable: true,
>         },
>         {
>             selector: 'model',
>             type: 'text',
>             label: 'مدل',
>             col: 4,
>             isRequired: true,
>             editable: true,
>         },
>         {
>             selector: 'serial',
>             type: 'text',
>             label: 'سریال',
>             col: 4,
>             isRequired: true,
>             editable: true,
>         },
>         {
>             selector: 'terminal_id',
>             type: 'text',
>             label: 'ترمینال',
>             col: 4,
>             isRequired: true,
>             editable: true,
>         },
>         {
>             selector: 'imei',
>             type: 'text',
>             label: 'IME',
>             col: 4,
>             isRequired: true,
>             editable: true,
>         },
>     ]
>     render() {
>         return (
>             <React.Fragment>
>                 <SmartCrud
>                     title="لیست دستگاه ها  "
>                     inputs={this.inputs}
>                     editable
>                     deletable
>                     //debug
>                     mutators={{
>                         onEdit: (data) => {
>                             console.log(data)
>                             return data
>                         },
>                         onSubmit: (data) => {
>                             console.log(data)
>                             return data
>                         },
>                         onSubmitEdit: (data) => {
>                             console.log(data)
>                             return data
>                         },
>                     }}
>                     route={DTK.TERMINALS}
>                     columns={this.columns}
>                     filters={this.filter}
>                     relations={['bank']}
>                     //appendFilter={[['application.clubs.id', '=', access.club.id]]}
>                 />
>             </React.Fragment>
>         )
>     }
> }
> export default Terminals
> ```

add `optionLabelSelector` config for select and multiselect input Types

install version 1.1.0

`yarn add jelly-smart-crud@1.1.0`
