### ISSUE TITLE
گزارش ایرادات پکیج اسمارت کراد

### ISSUE THREAD

**Issue by VahidMolaeiRad** [owlpro/jelly#2]
1. در قسمت نمایش پنل رنگ ایکون ها  و اندازشون فرق داره مثلا (قسمت ایجاد و...)
2. فونت متن ها فرقداره
3. در قسمت پایین  قسمت پیج بندی و نمایش صفحات رنگ ابی  که روی شماره یک ثابت میباشد در پکیج وجود ندارد
4. در قسمت عملیات  (ویرایش و ..) بهم ریخته هستش و ایکون ها متفاوت هستش
5. قسمت ایجاد کردن    قسمت انتخاب از دراب دان ظاهرش مشکل داره
6. قسمت ایجاد کردن  => دکمه های ایجاد و بستن مشکل داره
7. در قسمت ویرایش => فونت مشکل داره 
8. قسمت ویرایش => قسمت انتخاب از دراپ دان ظاهرش مشکل داره و همچنین دکمه ها هم استایلشون مشکل داره
9. در هنگام لودینگ شدن چند لحظه صفحه به حالت اسکرول در می ایید

**Comment by owlpro** [comment]
`yarn add jelly-smart-crud@1.1.1 `

### for resolve font problems (on your index and SmartCrudProvider):
import `createMuiTheme` from `@material-ui/core` and make a MUi theme
```
import { createMuiTheme } from '@material-ui/core'
import { blue } from '@material-ui/core/colors'

const theme = createMuiTheme({
    palette: {
        primary: blue, // <= for primary color
    },
    input: {
        height: 38,
        fontSize: 14,
    },
    button: {
        height: 38,
    },
    direction: 'rtl',
    typography: {
        fontFamily: "vazir",
        fontSize: 14,
    },
})
```

use your theme on SmartCrudProvider with `theme` attribute

```
ReactDOM.render(
    <SmartCrudProvider axios={axios} theme={theme}>
        <App />
    </SmartCrudProvider>,
    document.getElementById('root')
)
```
